name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test_path:
        description: 'Test path. Default: tests/saucedemo'
        required: false
        default: 'tests/saucedemo'
        type: string
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SAUCEDEMO_USERNAME: ${{ secrets.SAUCEDEMO_USERNAME }}
      SAUCEDEMO_PASSWORD: ${{ secrets.SAUCEDEMO_PASSWORD }}
      ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
      ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}
      TEST_PATH: ${{ inputs.test_path || 'tests/saucedemo' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests with JSON report
      shell: bash
      run: npx playwright test --reporter=json "$TEST_PATH" > playwright-report.json
    - name: Upload JSON Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-json-report
        path: playwright-report.json
        retention-days: 30
    - name: Send report to Slack
      if: always()
      run: node slack-playwright-report.js
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
