name: Playwright Scheduled Test

on:
  schedule:
    - cron: '0 8 * * *'  # Jalankan setiap hari pukul 08:00 UTC
  workflow_dispatch:  # Bisa juga dijalankan manual dari GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with HTML report
        run: npx playwright test --reporter=html

      - name: Upload HTML Report
        if: always()  # Selalu upload, meskipun tes berhasil/gagal
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
